### ISSUE TITLE
include AWS hostname as part of vault path

### ISSUE THREAD

**Issue by jasoncoposky** [irods/irods_resource_plugin_s3#1818]
the current fork of libs3 does not allow for the specification of any hostname other than the default.  move to a fork that does allow the specification and consider this as part of the vault path.

https://groups.google.com/forum/m/#!topic/irod-chat/IZrvl4y7vCs

**Comment by kellerb** [comment]
From https://github.com/wido/libs3
> The changes in this fork have been incorporated upstream. Please use Bryan's
repository instead of this one. If you encounter issues with libs3, please
report them upstream to Bryan.

So we should only need to pull in a newer version of current libs3
