### ISSUE TITLE
Multiple S3 resources on same resource server

### ISSUE THREAD

**Issue by othmar-weber** [irods/irods_resource_plugin_s3#1825]
It seems that only one S3 resource works per resource Server.

We have two compound resources with two different S3 resources defined at the same resource server.

We were not able to access both at the same time. With log level set to 7 we found out that the context string of one resource seems to overwrite the other.

Trace ouput:
```
Feb 10 10:40:37 pid:11292 DEBUG: environment variable set, irodsLogLevel(input)=7, value=7
Feb 10 10:40:37 pid:11292 DEBUG: context: S3_DEFAULT_HOSTNAME=system1;S3_AUTH_FILE=/var/lib/irods/.Auth1;S3_RETRY_COUNT=3;S3_WAIT_TIME_SEC=3;S3_PROTO=HTTP
Feb 10 10:40:37 pid:11292 DEBUG: vals: S3_DEFAULT_HOSTNAME system1
Feb 10 10:40:37 pid:11292 DEBUG: vals: S3_AUTH_FILE /var/lib/irods/.Auth1
Feb 10 10:40:37 pid:11292 DEBUG: vals: S3_RETRY_COUNT 3
Feb 10 10:40:37 pid:11292 DEBUG: vals: S3_WAIT_TIME_SEC 3
Feb 10 10:40:37 pid:11292 DEBUG: vals: S3_PROTO HTTP
Feb 10 10:40:37 pid:11292 DEBUG: context: S3_DEFAULT_HOSTNAME=system2;S3_AUTH_FILE=/var/lib/irods/.Auth2;S3_RETRY_COUNT=3;S3_WAIT_TIME_SEC=3;S3_PROTO=HTTP
Feb 10 10:40:37 pid:11292 DEBUG: vals: S3_DEFAULT_HOSTNAME system2
Feb 10 10:40:37 pid:11292 DEBUG: vals: S3_AUTH_FILE /var/lib/irods/.Auth2
Feb 10 10:40:37 pid:11292 DEBUG: vals: S3_RETRY_COUNT 3
Feb 10 10:40:37 pid:11292 DEBUG: vals: S3_WAIT_TIME_SEC 3
Feb 10 10:40:37 pid:11292 DEBUG: vals: S3_PROTO HTTP
```
It should be possible to have two different S3 resources defined to the same resource server ...

**Comment by jasoncoposky** [comment]
I see that the S3_AUTH_FILE, and S3_DEFAULT_HOSTNAME both parse out as unique values which are contained as properties within the plugins themselves.

The only way i could see that you could possibly run into a conflict is that libs3 is maintaining some global state when you have a single connection to iRODS which access multiple resources simultaneously.

Is this reproducible using icommands (which would use separate connections) ?

Which client(s) are you using when you run into this issue?

Also which versions are you using of iRODS and our S3 plugin?

**Comment by othmar-weber** [comment]
I checked to login with two different sessions. 

 session 1 access to datasource 1: error
 session 2 access to datasource 2: success
 session 1 access to datasource 2: error
 session 2 access to datasource 1: success
 session 1 access to datasource 1: error
 session 2 access to datasource 1: error

The behaviour does not seem to be predictable. If I configure both connections with the same parameters I can access just one data source but success rate is 100%.

We are using iRODS version 4.0.3 and plugin version is 1.3 compiled for 4.0.3.

**Comment by jasoncoposky** [comment]
Can  you post the errors from the iRODS server log?

Also I do not believe we have no had an official release of the 1.3 version of S3.  That will follow our iRODS 4.1.8 release.

**Comment by jasoncoposky** [comment]
I have just pushed a commit bafdf862ab6588e5fd806e148ecedd5c1195012a which will address this problem.  We use libs3 which does not behave well when used by the same process to access multiple S3 endpoints.  This solution will hold as long as the same connection is not used to access multiple iRODS S3 resource plugins. I have opened #1826 to address this issue in the future.

Please pull and rebuild your plugin to confirm on your end.
