### ISSUE TITLE
libs3 does not allow for connection to multiple S3 endpoints

### ISSUE THREAD

**Issue by jasoncoposky** [irods/irods_resource_plugin_s3#1826]
libs3 utilizes a set of global variables which prevents the access of multiple S3 endpoints from within the same process. This will need to be refactored to utilize a connection context whose lifetime may be managed by the S3 iRODS plugin to provide access to an arbitrary number of endpoints from the same iRODS Agent instance.

**Comment by earlephilhower** [comment]
I believe this is addressed with the latest 4.1.9 version.  Multiple S3 endpoints are specified in the resource definition line (comma separated) and they're rotated across as different connections are made.

**Comment by trel** [comment]
Closing for 1.4 release.
@earlephilhower and @jasoncoposky, if this still an issue, let's open another with specifics.
