### ISSUE TITLE
Unable to install resource plugin

### ISSUE THREAD

**Issue by coffes1** [irods/irods_resource_plugin_s3#1834]
Hi,

I am following the steps listed here in order to install the iRODS S3 Resource Plugin:  https://github.com/irods/irods_resource_plugin_s3

However, I am having issues building the resource plugin.  It fires "S3SignatureVersion does not name a type" errors:
```bash
root@vmubuntu3131:/# ./tmp/irods_resource_plugin_s3/packaging/build.sh

+------------------------------------+
| iRODS Plugin Build Script          |
+------------------------------------+
Wed Sep  7 11:01:05 IST 2016


Build Environment...
Detected OS                         [Ubuntu]
Detected OS Version                 [14.04]
Detected Plugin Name                [irods_resource_plugin_s3]
Detected EPM Package Name           [irods-resource-plugin-s3]
Detected Plugin Version to Build    [1.4]
Detected Plugin Version Integer     [140]
Detected Project Directory          [/tmp/irods_resource_plugin_s3]
Detected Packaging Directory        [/tmp/irods_resource_plugin_s3/packaging]
Detected Target Build Directory     [/tmp/irods_resource_plugin_s3/build]
Detected EPM List File              [/tmp/irods_resource_plugin_s3/packaging/irods_resource_plugin_s3.list]
Detected CPUs                       [4]
Compile Command                     [make -j 7]

Building...
make -C s3
make[1]: Entering directory `/tmp/irods_resource_plugin_s3/s3'
g++ -DRODS_SERVER -I/usr/include/irods/boost -I/usr/include/irods -I/usr/include/openssl  -O3 -fPIC -c -o .objs/libirods_s3.o libirods_s3.cpp
libirods_s3.cpp:395:12: error: âS3SignatureVersionâ does not name a type
     static S3SignatureVersion s3GetSignatureVersion (irods::plugin_property_map& _prop_map)
            ^
libirods_s3.cpp: In function âirods::error s3Init(irods::plugin_property_map&)â:
libirods_s3.cpp:549:17: error: âS3SignatureVersionâ was not declared in this scope
                 S3SignatureVersion signature_version = s3GetSignatureVersion(_prop_map);
                 ^
libirods_s3.cpp:549:36: error: expected â;â before âsignature_versionâ
                 S3SignatureVersion signature_version = s3GetSignatureVersion(_prop_map);
                                    ^
libirods_s3.cpp:551:21: error: âsignature_versionâ was not declared in this scope
                 if (signature_version == S3SignatureV4) {
                     ^
libirods_s3.cpp:551:42: error: âS3SignatureV4â was not declared in this scope
                 if (signature_version == S3SignatureV4) {
                                          ^
libirods_s3.cpp:552:30: error: âS3_INIT_SIGNATURE_V4â was not declared in this scope
                     flags |= S3_INIT_SIGNATURE_V4;
                              ^
libirods_s3.cpp:570:25: error: âsignature_versionâ was not declared in this scope
                     if (signature_version == S3SignatureV4) {
                         ^
libirods_s3.cpp:570:46: error: âS3SignatureV4â was not declared in this scope
                     if (signature_version == S3SignatureV4) {
                                              ^
libirods_s3.cpp:578:81: error: âS3_set_region_nameâ was not declared in this scope
                         S3Status status = S3_set_region_name(region_name.c_str());
                                                                                 ^
libirods_s3.cpp: In function âbool s3GetEnableMD5(irods::plugin_property_map&)â:
libirods_s3.cpp:667:44: error: âs3GetSignatureVersionâ was not declared in this scope
         if (s3GetSignatureVersion(_prop_map) == S3SignatureV4) {
                                            ^
libirods_s3.cpp:667:49: error: âS3SignatureV4â was not declared in this scope
         if (s3GetSignatureVersion(_prop_map) == S3SignatureV4) {
                                                 ^
libirods_s3.cpp: At global scope:
libirods_s3.cpp:804:12: error: âS3STSDateâ does not name a type
     static S3STSDate s3GetSTSDate( irods::plugin_property_map& _prop_map)
            ^
libirods_s3.cpp: In function âirods::error s3GetFile(const string&, const string&, rodsLong_t, const string&, const string&, irods::plugin_property_map&)â:
libirods_s3.cpp:860:35: error: âS3BucketContextâ has no member named âstsDateâ
                     bucketContext.stsDate = s3GetSTSDate(_prop_map);
                                   ^
libirods_s3.cpp:860:67: error: âs3GetSTSDateâ was not declared in this scope
                     bucketContext.stsDate = s3GetSTSDate(_prop_map);
                                                                   ^
libirods_s3.cpp: In function âvoid mpuCancel(S3BucketContext*, const char*, const char*)â:
libirods_s3.cpp:1121:9: error: âS3AbortMultipartUploadHandlerâ was not declared in this scope
         S3AbortMultipartUploadHandler abortHandler = { { mpuCancelRespPropCB, mpuCancelRespCompCB } };
         ^
libirods_s3.cpp:1121:39: error: expected â;â before âabortHandlerâ
         S3AbortMultipartUploadHandler abortHandler = { { mpuCancelRespPropCB, mpuCancelRespCompCB } };
                                       ^
libirods_s3.cpp:2469:1: error: expected â}â at end of input
 } // extern "C"
 ^
libirods_s3.cpp: At global scope:
libirods_s3.cpp:2469:1: error: expected â}â at end of input
make[1]: *** [.objs/libirods_s3.o] Error 1
make[1]: Leaving directory `/tmp/irods_resource_plugin_s3/s3'
make: *** [s3] Error 2
root@vmubuntu3131:/#
```

I haven't found any related ticket for this issue.

Can you assist please?

Thanks!

**Comment by adetorcy** [comment]
You might not have the right version of libs3 (with signature V4 support). Are you using version 4.1.9 of the dev and runtime packages?

If building libs3 from source you will need our [v4](https://github.com/irods/libs3/tree/v4) branch.

**Comment by coffes1** [comment]
Hi,

Yes, I was using iRODS 4.1.8.  I have now reverted back to a 4.1.9 snapshot.  However, I'm still having issues when putting files into a S3 bucket:

irods@vmubuntu3131:/tmp$ iput -R compResc1 test1.txt
ERROR: putUtil: put error for /tempZone/home/rods/test1.txt, status = -1818000 status = -1818000 INVALID_ACCESS_TO_IMPOSTOR_RESOURCE
NOTE :: Direct Access of Impostor Resource [archiveResc1] of Given Type [s3]
NOTE :: Direct Access of Impostor Resource [archiveResc1] of Given Type [s3]

And in the rodsLog:

Sep  7 15:09:43 pid:1087 NOTICE: Agent process 4456 started for puser=rods and cuser=rods from 10.64.31.31
Sep  7 15:09:43 pid:4456 ERROR: [-]     iRODS/server/api/src/rsFileSyncToArch.cpp:190:_rsFileSyncToArch :  status [INVALID_ACCESS_TO_IMPOSTOR_RESOURCE]  errno [] -- message [fileSyncToArch failed for [/irods/vault/home/rods/test1.txt]]
        [-]     iRODS/server/drivers/src/fileDriver.cpp:612:fileSyncToArch :  status [INVALID_ACCESS_TO_IMPOSTOR_RESOURCE]  errno [] -- message [failed to call 'synctoarch']
                [-]     iRODS/server/core/src/irods_resource_plugin_impostor.cpp:525:report_error :  status [INVALID_ACCESS_TO_IMPOSTOR_RESOURCE]  errno [] -- message [NOTE :: Direct Access of Impostor Resource [archiveResc1] of Given Type [s3]]

Sep  7 15:09:43 pid:4456 ERROR: _rsDataObjClose - getSizeInVault failed [-1818000]
Sep  7 15:09:43 pid:4456 NOTICE: rsDataObjRepl - Failed to replicate data object.
Sep  7 15:09:43 pid:4456 ERROR: [-]     iRODS/server/api/src/rsModDataObjMeta.cpp:257:_call_file_modified_for_modification :  status [INVALID_ACCESS_TO_IMPOSTOR_RESOURCE]  errno [] -- message [_call_file_modified_for_modification - Failed to signal the resource that the data object "/tempZone/home/rods/test1.txt" was modified.]
        [-]     iRODS/server/drivers/src/fileDriver.cpp:723:fileModified :  status [INVALID_ACCESS_TO_IMPOSTOR_RESOURCE]  errno [] -- message [fileModified - Failed to call modified interface.]
                [-]     libcompound.cpp:496:repl_object :  status [INVALID_ACCESS_TO_IMPOSTOR_RESOURCE]  errno [] -- message [Failed to replicate the data object [/tempZone/home/rods/test1.txt] for operation [sync_object]]

Sep  7 15:09:43 pid:4456 NOTICE: readAndProcClientMsg: received disconnect msg from client
Sep  7 15:09:43 pid:4456 NOTICE: Agent exiting with status = 0
Sep  7 15:09:44 pid:1087 NOTICE: Agent process 4456 exited with status 0

My S3 authentication file contains the correct username/secret key.  I have tried connecting to a few different S3 lab boxes (changed the credentials each time).  However, the issue persists.

Thanks!

**Comment by adetorcy** [comment]
That looks similar to [this issue](https://groups.google.com/forum/#!topic/irod-chat/BGLsxr8nEm8).
Please check the details of your setup, and if necessary list them here.

**Comment by coffes1** [comment]
Hi,

I checked that ticket.  I do **not** have the referenced file on my Ubuntu system:

root@vmubuntu3131:/# ls -l /var/lib/irods/plugins/resources/libs3.so
ls: cannot access /var/lib/irods/plugins/resources/libs3.so: No such file or directory

I have followed this Readme for the plugin:

https://github.com/irods/irods_resource_plugin_s3

I believe that I have installed all the relevant libs.  

Let me know what other details you need from the machine.

Thanks!

**Comment by coffes1** [comment]
By the way, I'm connecting iRODS to a non-Amazon S3 box.  It worked fine a few months ago with 4.1.8 but have yet to get it working with 4.1.9.

Thanks.

**Comment by trel** [comment]
You need to install the .deb package that gets built - this will put the libs3.so file in the correct place.

Otherwise, your iRODS installation will not know how to communicate with the S3 endpoint.

**Comment by coffes1** [comment]
Yep, I have already installed these .deb packages:

irods-icat-4.1.9-ubuntu14-x86_64.deb
irods-database-plugin-postgres-1.9-ubuntu14-x86_64.deb
irods-runtime-4.1.9-ubuntu14-x86_64.deb
irods-dev-4.1.9-ubuntu14-x86_64.deb

Thanks!

**Comment by trel** [comment]
You need to install the newly built irods-resource-plugin-s3 .deb.

**Comment by coffes1** [comment]
Hi,

It appears that the S3 plugin is only for iRODS 4.1.8 as per http://irods.org/download/

Resource Plugins
irods-resource-plugin-s3-1.3 (compatible with 4.1.8 only)
source and usage
Ubuntu 12 deb
Ubuntu 14 deb
CentOS 6 rpm
CentOS 7 rpm
OpenSUSE 13 rpm

I've got 4.1.9 installed.  I went ahead and tried to install it but, as expected, it fired an error:

root@vmubuntu3131:/tmp# dpkg -i irods-resource-plugin-s3-1.3-ubuntu14-x86_64.deb
Selecting previously unselected package irods-resource-plugin-s3.
(Reading database ... 116203 files and directories currently installed.)
Preparing to unpack irods-resource-plugin-s3-1.3-ubuntu14-x86_64.deb ...
Local iRODS is 4.1.9
This plugin requires iRODS 4.1.8
dpkg: error processing archive irods-resource-plugin-s3-1.3-ubuntu14-x86_64.deb (--install):
 subprocess new pre-installation script returned error exit status 1
Errors were encountered while processing:
 irods-resource-plugin-s3-1.3-ubuntu14-x86_64.deb
root@vmubuntu3131:/tmp#

Is there not a version of the plugin for 4.1.9?

Thanks!

**Comment by trel** [comment]
We are releasing the 1.4 version within a day or so.

I thought you were building the s3 resource plugin from source.  If so, like @adetorcy said...

> If building libs3 from source you will need our [v4](https://github.com/irods/libs3/tree/v4) branch.

That will be compatible with 4.1.9.

**Comment by coffes1** [comment]
Thanks!  I'll check back here with you guys in a few days (maybe next Mon) re the 1.4 version.

**Comment by adetorcy** [comment]
The S3 resource plugin package on http://irods.org/download/ is for iRODS 4.1.8.

When you downloaded/cloned this code from github and ran `./tmp/irods_resource_plugin_s3/packaging/build.sh` you built a new S3 resource plugin package for your iRODS 4.1.9 install. The new package should be in `./tmp/irods_resource_plugin_s3/build/`. Try installing that one.

**Comment by coffes1** [comment]
Hi folks,

Something is messed up because I don't have this:

/tmp/irods_resource_plugin_s3/packaging/build.sh

Is the 1.4 version now available?

Thanks!

**Comment by trel** [comment]
I will release it later today and update this thread

**Comment by coffes1** [comment]
Thanks trel!

**Comment by trel** [comment]
1.4 has been tagged and released.

Please open a new issue if you have trouble with the code.
