### ISSUE TITLE
"Access Denied" error in rodsLog when putting a file into S3 bucket

### ISSUE THREAD

**Issue by coffes1** [irods/irods_resource_plugin_s3#1835]
Hi folks,

Please reference my previous ticket;  https://github.com/irods/irods_resource_plugin_s3/issues/1834

I installed the new 1.4 S3 .deb package a few days ago.  It looks good as I now no longer get "Direct Access of Impostor Resource" errors when putting files.  However, there still appears to be some issue as per the following:
```bash
irods@vmubuntu3131:/tmp$ iput -R complab test9
ERROR: putUtil: put error for /tempZone/home/rods/test9, status = -702000 status = -702000 S3_PUT_ERROR

The rodsLog reveals the following:

Sep 13 18:43:29 pid:5575 NOTICE: Agent process 17574 started for puser=rods and cuser=rods from 10.64.31.31
Sep 13 18:43:29 pid:17574 ERROR: [-]    iRODS/lib/core/include/irods_lookup_table.hpp:149:get :  status [KEY_NOT_FOUND]  errno [] -- message [failed to find key [ARCHIVE_NAMING_POLICY] in table.]

Sep 13 18:43:29 pid:17574 ERROR:   S3Status: [ErrorAccessDenied] - 48
Sep 13 18:43:29 pid:17574 ERROR:     S3Host: 10.247.71.205:9020
Sep 13 18:43:29 pid:17574 ERROR:   Function: responseCompleteCallback
Sep 13 18:43:29 pid:17574 ERROR:   Message: Access Denied
Sep 13 18:43:29 pid:17574 ERROR:   Extra Details:
Sep 13 18:43:29 pid:17574 ERROR:     RequestId: 0af747cd:156eb5ed3b5:17ad:0
Sep 13 18:43:32 pid:17574 ERROR: [-]    libirods_s3.cpp:2232:s3SyncToArchPlugin :  status [S3_PUT_ERROR]  errno [] -- message [Failed to copy the cache file: "/var/lib/irods/iRODS/ECSCacheVaultlab/home/rods/test9" to the S3 object: "/irods_lab/vault/home/rods/test9".]
        [-]     libirods_s3.cpp:1340:s3PutCopyFile :  status [S3_PUT_ERROR]  errno [] -- message [s3PutCopyFile - Error putting the S3 object: "/irods_lab/vault/home/rods/test9" - "ErrorAccessDenied"]

Sep 13 18:43:32 pid:17574 ERROR: [-]    iRODS/server/api/src/rsFileSyncToArch.cpp:190:_rsFileSyncToArch :  status [S3_PUT_ERROR]  errno [] -- message [fileSyncToArch failed for [/irods_lab/vault/home/rods/test9]]
        [-]     iRODS/server/drivers/src/fileDriver.cpp:612:fileSyncToArch :  status [S3_PUT_ERROR]  errno [] -- message [failed to call 'synctoarch']
                [-]     libirods_s3.cpp:2232:s3SyncToArchPlugin :  status [S3_PUT_ERROR]  errno [] -- message [Failed to copy the cache file: "/var/lib/irods/iRODS/ECSCacheVaultlab/home/rods/test9" to the S3 object: "/irods_lab/vault/home/rods/test9".]
                        [-]     libirods_s3.cpp:1340:s3PutCopyFile :  status [S3_PUT_ERROR]  errno [] -- message [s3PutCopyFile - Error putting the S3 object: "/irods_lab/vault/home/rods/test9" - "ErrorAccessDenied"]

Sep 13 18:43:33 pid:17574 ERROR: [-]    libirods_s3.cpp:1966:s3FileStatPlugin :  status [S3_FILE_STAT_ERR]  errno [] -- message [s3FileStatPlugin - S3 object not found: "/irods_lab/vault/home/rods/test9"]

Sep 13 18:43:33 pid:17574 ERROR: _rsDataObjClose - getSizeInVault failed [-716000]
Sep 13 18:43:33 pid:17574 NOTICE: rsDataObjRepl - Failed to replicate data object.
Sep 13 18:43:33 pid:17574 ERROR: [-]    iRODS/server/api/src/rsModDataObjMeta.cpp:257:_call_file_modified_for_modification :  status [S3_PUT_ERROR]  errno [] -- message [_call_file_modified_for_modification - Failed to signal the resource that the data object "/tempZone/home/rods/test9" was modified.]
        [-]     iRODS/server/drivers/src/fileDriver.cpp:723:fileModified :  status [S3_PUT_ERROR]  errno [] -- message [fileModified - Failed to call modified interface.]
                [-]     libcompound.cpp:496:repl_object :  status [S3_PUT_ERROR]  errno [] -- message [Failed to replicate the data object [/tempZone/home/rods/test9] for operation [sync_object]]

Sep 13 18:43:33 pid:17574 NOTICE: readAndProcClientMsg: received disconnect msg from client
Sep 13 18:43:33 pid:17574 NOTICE: Agent exiting with status = 0
Sep 13 18:43:33 pid:5575 NOTICE: Agent process 17574 exited with status 0
```
There is an "Access Denied" error.  However, I have double checked that my S3 authentication file is good - it simply contains the username on the first line and the secret key on the second line.  I successfully verified reads/writes to the bucket outside of iRODS via S3 Browser.

I don't understand this error: "failed to find key [ARCHIVE_NAMING_POLICY] in table".  Is that a possible cause of the issue?

By the way, the links for the S3 plugin under irods-resource-plugin-s3-1.4 on http://irods.org/download/ are broken e.g.:

Broken link:  ftp://ftp.renci.org/pub/irods/plugins/irods_resource_plugin_s3/1.4/irods-resource-plugin-s3-1.4-ubuntu14-x86_64.deb

The OS is missing.  This is the correct link for the above .deb:

ftp://ftp.renci.org/pub/irods/plugins/irods_resource_plugin_s3/1.4/ubuntu14/irods-resource-plugin-s3-1.4-ubuntu14-x86_64.deb

Thanks!

**Comment by trel** [comment]
You are correct about the FTP locations - I have updated them to be correct.

**Comment by adetorcy** [comment]
ARCHIVE_NAMING_POLICY is an optional setting so that's not the problem. Try using the following in your S3 authentication file (the one used by your resource plugin):
Access Key ID
Secret Access Key

**Comment by coffes1** [comment]
Hi Antoine,

That's exactly what my authentication file contains.  The credentials work perfectly fine outside of iRODS.  I believe the permissions/ownership of the file looks good too:

irods@vmubuntu3131:~/iRODS/server/log$ ls -lart /var/lib/irods/.bucket_auth
-rw------- 1 irods irods 49 Sep 13 18:36 /var/lib/irods/.bucket_auth

Thanks.

**Comment by adetorcy** [comment]
You wrote earlier that you were using your username in your authentication file. Just to be sure, your S3 username and Access Key ID are not the same thing (see [here](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSGettingStartedGuide/AWSCredentials.html)).

What other tools are you using to access your S3 bucket?

**Comment by coffes1** [comment]
Yep, I'm using the object user (Access Key ID).  I have verified that the credentials are good for accessing the bucket in question via S3 Browser.  I'm not sure why iRODS is firing the "Access Denied" error.

Thanks.

**Comment by coffes1** [comment]
I deliberately added an erroneous secret key to the auth file.  The rodsLog subsequently fires this error when I try to put an object:

Sep 14 15:34:30 pid:23047 ERROR:   S3Status: [ErrorSignatureDoesNotMatch] - 116
Sep 14 15:34:30 pid:23047 ERROR:     S3Host: 10.247.71.205:9020
Sep 14 15:34:30 pid:23047 ERROR:   Function: responseCompleteCallback
Sep 14 15:34:30 pid:23047 ERROR:   Message: The request signature we calculated does not match the signature you provided. Check your Secret Access Key and signing method. For more information, see REST Authentication and SOAP Authentication for details.

The above errors are not fired when I use the correct key.

Thanks.

**Comment by adetorcy** [comment]
You might want to check your bucket policy then and make sure you have permission to list the bucket contents.

**Comment by coffes1** [comment]
Hi,

The user that owns the bucket has full read/write permissions for it.

Could this be an issue with the S3 Signature version?  Is v4 being used by iRODS now?  The S3 product that I am using currently only supports v3.

Keep in mind that I had no issues with iRODS/S3 integration a few months ago when I tested with iRODS 4.1.9/S3 plugin 1.3.

Thanks,
Seamus

**Comment by adetorcy** [comment]
Version 1.4 of the S3 resource plugin supports AWS Signature V2 and V4, and defaults to V2 unless `S3_SIGNATURE_VERSION=4` is specified in the resource context. Version 1.3 of the S3 resource plugin supports AWS Signature V2 only.

AWS usually gives you an explicit response when there is an issue with your signature, but your appliance might be different.
Have you tried printing out the contents of your canonical request?

**Comment by coffes1** [comment]
Hi folks,

iRODS is still not able to put the objects in question into the S3 bucket.  Here is the relevant log on the S3 side - note that the PUT fails (HTTP 403 error) but then the GET is successful (HTTP 200 OK):

2016-09-20T10:35:17,155 [qtp896945135-5515]  INFO  RequestLog.java (line 83) 10.64.31.31 PUT //10.245.129.41:9020/valencia/irods/Vault/home/rods/valencia88 HTTP/1.1 403 5 - 121
2016-09-20T10:35:21,435 [qtp896945135-5515]  INFO  RequestLog.java (line 83) 10.64.31.31 GET //10.245.129.41:9020/valencia/?prefix=irods%2FVault%2Fhome%2Frods%2Fvalencia88&max-keys=1 HTTP/1.1 200 24 - 343

Thanks.

**Comment by adetorcy** [comment]
What does a successful PUT request (e.g. from S3 Browser) look like?

**Comment by coffes1** [comment]
Hi,

Here is a successful PUT from S3 Browser:

2016-09-20T13:15:14,304 [qtp896945135-6540]  INFO  RequestLog.java (line 83) 10.64.28.68 PUT //10.245.129.41:9020/valencia/sevilla.txt HTTP/1.1 200 540 85 -
2016-09-20T13:15:14,464 [qtp896945135-6534]  INFO  RequestLog.java (line 83) 10.64.28.68 GET //10.245.129.41:9020/valencia/?delimiter=%2F&max-keys=1000 HTTP/1.1 200 44 - 590

Thanks

**Comment by adetorcy** [comment]
Can you put `/valencia/irods/Vault/home/rods/valencia88` from the S3 Browser?

**Comment by coffes1** [comment]
No issues from S3 Browser with valencia88:

2016-09-20T13:46:33,792 [qtp896945135-6640]  INFO  RequestLog.java (line 83) 10.64.28.68 PUT //10.245.129.41:9020/valencia/valencia88.txt HTTP/1.1 200 504 54 -
2016-09-20T13:46:33,935 [qtp896945135-6600]  INFO  RequestLog.java (line 83) 10.64.28.68 GET //10.245.129.41:9020/valencia/?delimiter=%2F&max-keys=1000 HTTP/1.1 200 33 - 845

**Comment by adetorcy** [comment]
Can you put `/valencia/irods/Vault/home/rods/valencia88` from the S3 Browser? Not just `/valencia/valencia88.txt`. In other words, does your appliance allows for `/` in S3 key names?

**Comment by coffes1** [comment]
Hi,

I just tried that via S3 Browser - I created three "subfolders" under valencia and then successfully PUT a file:

Key: valenciasub1/valenciasub2/valenciasub3/valencia88.txt

Thanks.

**Comment by adetorcy** [comment]
OK now try making subfolders as follows `/valencia/irods/Vault/home/rods/` and then try again to put a file from irods, as user `rods`. Please print the requests.

**Comment by coffes1** [comment]
Hi,

Quick question - how do I modify an existing archive resource?  Here is the command that I used to create it originally:

iadmin mkresc archivevalencia s3 vmubuntu3131:/valencia/irods/Vault "S3_DEFAULT_HOSTNAME=10.245.129.41:9020;S3_AUTH_FILE=/var/lib/irods/.s3_auth;S3_RETRY_COUNT=3;S3_WAIT_TIME_SEC=3;S3_PROTO=HTTP"

I guess I need to use "modresc" but I'm unsure of the arguments.

Thanks!

**Comment by adetorcy** [comment]
`iadmin modresc archivevalencia context "S3_DEFAULT_HOSTNAME=10.245.129.41:9020;S3_AUTH_FILE=/var/lib/irods/.s3_auth;S3_RETRY_COUNT=3;S3_WAIT_TIME_SEC=3;S3_PROTO=HTTP"`

**Comment by coffes1** [comment]
What takes the place of "context"? "s3 hostname:<bucket/subdir/subdir>"?  I only want to change the bucket as per your previous recommendation.  The command errors out:

irods@vmubuntu3131:~/iRODS/server/log$ iadmin modresc archivevalencia s3 vmubuntu3131:/valencia/irods/Vault/home/rods/ "S3_DEFAULT_HOSTNAME=10.245.129.41:9020;S3_AUTH_FILE=/var/lib/irods/.s3_auth;S3_RETRY_COUNT=3;S3_WAIT_TIME_SEC=3;S3_PROTO=HTTP"
ERROR: rcGeneralAdmin failed with error -816000 CAT_INVALID_ARGUMENT

Thanks,
Seamus

**Comment by coffes1** [comment]
Let me know if you guys actually want to see this environment at some stage - I can setup a remote WebEx session.  It might save us time constantly going over and back on this ticket.

Thanks!

**Comment by adetorcy** [comment]
Sure, please send us some details through our [contact form](http://irods.org/contact/)

**Comment by coffes1** [comment]
Thanks, I'll send a remote session link via the contact form if I am free tomorrow afternoon European CEST.

**Comment by coffes1** [comment]
Hey folks,

I'll contact you via the Contact form some day next week.  Busy with other issues at the moment.

Thanks.
