### ISSUE TITLE
install instruction for irods < 4.1.10

### ISSUE THREAD

**Issue by beheerderdag** [irods/irods_resource_plugin_s3#1839]
I think the install instruction can be made little bit clearer. I had some issues installing the s3 resource plugin in irods 4.1.8. 

After installing the prerequisites it was not clear how to install the resource plugin. So I didn't realise that I actually skipped that part. I got the "INVALID_ACCESS_TO_IMPOSTOR_RESOURCE" error when tried iput. Then I noticed the CMake script but that gave me the following error.  I am using (CentOS 6.9). 

```
root# cmake CMakeLists.txt 
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.5.0 or higher is required.  You are running version 2.8.12.2
```
Instead of building it with cmake I downloaded the rpm from here: [ftp://ftp.renci.org/pub/irods/plugins/irods_resource_plugin_s3/1.3/](ftp://ftp.renci.org/pub/irods/plugins/irods_resource_plugin_s3/1.3/)
Also, the irods download page does not have the link to the old versions. After that, I was able to get the plugin working with 4.1.8 but took me a while to go through the steps.

**Comment by trel** [comment]
The current instructions work for 4.2+.   Closing this as the release mechanisms have significantly changed since 4.1.x.
