### ISSUE TITLE
Move the metadata from Tier 0 to Archive Tier 1 in S3 Object storage

### ISSUE THREAD

**Issue by masilamani** [irods/irods_resource_plugin_s3#1841]
when user-defined metadata is added to data object in Tier 0, tiered storage framework is not moving the metadata along with data object into Archive Tier 1 in S3 Object storage.

Example:

```
imeta ls -d /DiaZone/home/rods/foo.txt
AVUs defined for dataObj /TestZone/home/rods/foo.txt:
attribute: ARCHIVE
value: Y
units:
```
After it is moved into S3 object storage, metadata shows empty when i run the aws s3api command as shown below.

```
aws s3api head-object --bucket --key 335321/foo.txt
{
  "AcceptRanges": "bytes",
  "ContentType": "binary/octet-stream",
  "LastModified": "Mon, 19 Mar 2018 02:19:23 GMT",
  "ContentLength": 15,
  "ETag": ""1846010d59652a3bb045580a44b12cf3"",
  "Metadata": {}
}
```

But it should have like this if AVU metadata is also moved along with data object.

```
{
  "AcceptRanges": "bytes",
  "ContentType": "binary/octet-stream",
  "LastModified": "Mon, 19 Mar 2018 02:19:23 GMT",
  "ContentLength": 15,
  "ETag": ""1846010d59652a3bb045580a44b12cf3"",
  "Metadata": {
    "archive": "Y"
  }
}
```

**Comment by trel** [comment]
I don't think this has anything to do with the storage tiering framework.

This is just a question of adding metadata information from the iRODS catalog to S3, either during or just after an update in iRODS.

Can it be done in a rule?

**Comment by trel** [comment]
iRODS does not populate/manage S3 metadata at this time.
