### ISSUE TITLE
Default for S3_ENABLE_MPU should be enabled not disabled

### ISSUE THREAD

**Issue by HowardLander** [irods/irods_resource_plugin_s3#1845]
The capacity to disable MPU mode was added to this driver when it was certified to run about GCS, which does not support MPU mode.  However we still want the default to be that MPU mode is enabled.

**Comment by trel** [comment]
should be set to true

https://github.com/irods/irods_resource_plugin_s3/blob/master/s3/libirods_s3.cpp#L715
