### ISSUE TITLE
add HOST_MODE context string option (support for cacheless and detached)

### ISSUE THREAD

**Issue by trel** [irods/irods_resource_plugin_s3#1849]
Implement context string option:
```
HOST_MODE=['archive_attached', 'cacheless_attached', 'cacheless_detached']
```

Default behavior is 'archive_attached'.

Upon HOST_MODE detection,
  - if `HOST_MODE != 'archive_attached'` AND `parent_context=archive`, then:
     - log a WARNING, alerting admin to inconsistent configuration
     - change behavior to 'archive_attached'

**Comment by JustinKyleJames** [comment]
This has been implemented.  Closing.
