### ISSUE TITLE
Support multiple streams writing in parallel in cacheless mode

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/irods_resource_plugin_s3#1862]
- [x] main
- [x] 4-2-stable
-----

When writing multiple streams to a file, the output is not as expected and not consistent with the unixfilesystem resource.

The output is correct when using an S3FS mount point instead of a cache-less S3 resource so the problem is not in the S3FS code itself.

Most likely I need to mimic the locking behavior found in the POSIX write() call.

**Comment by JustinKyleJames** [comment]
The problem here is that the multiple streams are being written by different processes. If the streams are being written by the same process (as is done with the large file upload/download in iRODS) then it works.

To fix this, the S3FS cache needs to be in shared memory.

**Comment by JustinKyleJames** [comment]
This has been fixed with the streaming S3 plugin.  Will close when that is closed.

**Comment by trel** [comment]
Is this working for main now too?

**Comment by trel** [comment]
@JustinKyleJames 

> Is this working for main now too?

**Comment by JustinKyleJames** [comment]
> @JustinKyleJames
> 
> > Is this working for main now too?

Yes, I will checkmark and close this issue.
