### ISSUE TITLE
Support Instance roles (STS)

### ISSUE THREAD

**Issue by datavisyn-ro-v** [irods/irods_resource_plugin_s3#1869]
Hi,

Currently it seems that onl AWS_KEY and AWS_SECRET_KEY are used.

We are running instances directly on AWS and have assigned EC2 instance roles. It seems the AWS SDK would support this by default (https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/credentials.html):

> For an EC2 instance, specify an IAM role and then give your EC2 instance access to that role. See IAM Roles for Amazon EC2 in the Amazon EC2 User Guide for Linux Instances for a detailed discussion about how this works.

That would allow us to use irods without having to care about credentials or having to rotate them.

**Comment by serverhorror** [comment]
sorry, I have submitted this from the wrong account :(

**Comment by trel** [comment]
Yes, similar to what I just wrote here... https://github.com/irods/irods_resource_plugin_s3/issues/1870

We are looking into solutions that can be Amazon agnostic - they need to work with S3 as a protocol.

Suggestions welcome.

**Comment by trel** [comment]
We have seen other services and appliances only support access and secret key credentials.

I don't expect this will change in the foreseeable future.  Closing.
