### ISSUE TITLE
Question: why is this thing not using the AWS C++ API?

### ISSUE THREAD

**Issue by bitkid** [irods/irods_resource_plugin_s3#1870]
distributing secret keys on instances is something you don't want to do, especially not when the instances are already EC2 instances where it's not needed. any plans to change that?

**Comment by trel** [comment]
Hi @bitkid, 

The short answer is that this work predates the AWS C++ API.

The longer answer involves time and attention and priority.  We have a longer term plan to incorporate Google Vault or some other secrets location, but it has not yet been at the top of the list of things to work on.

Are you interested in spearheading the work?  We're very happy to help.

**Comment by JustinKyleJames** [comment]
Also note that the AWS C++ API is designed to be a very high level API.  This mostly works in a similar manner as the AWS CLI API.  You select a file to get/put, etc.

This high level API doesn't meet our needs to have a more low level control where we are fed parts of the object from iRODS in parallel.

It should be possible to use the lower level interfaces that the high level API uses to achieve what we need.  I played around with it a bit but not long enough to get it to work.

**Comment by JustinKyleJames** [comment]
Also note that the AWS C++ API is designed to be a very high level API.  This mostly works in a similar manner as the AWS CLI API.  You select a file to get/put, etc.

This high level API doesn't meet our needs to have a more low level control where we are fed parts of the object from iRODS in parallel.

It should be possible to use the lower level interfaces that the high level API uses to achieve what we need.  I played around with it a bit but not long enough to get it to work.

**Comment by JustinKyleJames** [comment]
Also note that the AWS C++ API is designed to be a very high level API.  This mostly works in a similar manner as the AWS CLI API.  You select a file to get/put, etc.

This high level API doesn't meet our needs to have a more low level control where we are fed parts of the object from iRODS in parallel.

It should be possible to use the lower level interfaces that the high level API uses to achieve what we need.  I played around with it a bit but not long enough to get it to work.

**Comment by trel** [comment]
We will not be migrating this codebase to use AWS-specific codes.   Closing.
