### ISSUE TITLE
Support ireg -C option to register all files in bucket / folder in bucket

### ISSUE THREAD

**Issue by bitkid** [irods/irods_resource_plugin_s3#1881]
This would come super handy to us!

**Comment by trel** [comment]
I believe this already works... but it is relatively slow.

Alternately, you can have a look at the parallelized Automated Ingest tool (`n` times faster than `ireg`)
 - https://github.com/irods/irods_capability_automated_ingest

**Comment by bitkid** [comment]
does not seem to work .. i can register a single file in a bucket with `ireg -R s3ArchiveRescAJ /mybucket/xxx/somefile.zip /sascha2/home/sadatgus/somefile.zip` but when i use the -C option i get `remote addresses: 10.4.81.96 ERROR: regUtil: reg error for /sascha2/home/sadatgus/mycollectionii, status = -66000 status = -66000 SYS_NOT_SUPPORTED
 ERROR: main: regUtil error.  status = -66000 SYS_NOT_SUPPORTED` and in the log file on the resource server i see this message `Jun 19 08:45:12 pid:212 remote addresses: 10.4.81.96 ERROR: dirPathReg: rsFileOpendir for /mybucket/xxx error, status = -66000
Jun 19 08:45:37 pid:213 remote addresses: 10.4.81.96 ERROR: [-] /tmp/tmpfe6BJv/server/api/src/rsFileOpendir.cpp:120:int _rsFileOpendir(rsComm_t *, fileOpendirInp_t *, void **) :  status [SYS_NOT_SUPPORTED]  errno [] -- message [s3FileOpendirPlugin]
        [-]     /tmp/tmpfe6BJv/server/drivers/src/fileDriver.cpp:382:irods::error fileOpendir(rsComm_t *, irods::first_class_object_ptr) :  status [SYS_NOT_SUPPORTED]  errno [] -- message [s3FileOpendirPlugin]
                [-]     /tmp/tmpfe6BJv/plugins/resources/passthru/libpassthru.cpp:408:irods::error passthru_file_opendir(irods::plugin_context &) :  status [SYS_NOT_SUPPORTED]  errno [] -- message [s3FileOpendirPlugin]
                        [-]     /tmp/tmp919rQK/s3/libirods_s3.cpp:2119:irods::error s3FileOpendirPlugin(irods::plugin_context &) :  status [SYS_NOT_SUPPORTED]  errno [] -- message [s3FileOpendirPlugin]`

**Comment by JustinKyleJames** [comment]
The existing plugin returns a SYS_NOT_SUPPORTED on this operation.  This would require an enhancement to support this operation.

    // =-=-=-=-=-=-=-
    // interface for POSIX opendir
    irods::error s3FileOpendirPlugin( irods::plugin_context& _ctx ) { 

        return ERROR( SYS_NOT_SUPPORTED, "s3FileOpendirPlugin" );
    } // s3FileOpendirPlugin

**Comment by JustinKyleJames** [comment]
I would suggest at this point to either use automated ingest to get the objects registered or write a script that does this.  The first option would be more efficient.

**Comment by bitkid** [comment]
ok, thx for the info!

**Comment by JustinKyleJames** [comment]
This has been implemented.  Closing.
