### ISSUE TITLE
Unknown error in authorization file

### ISSUE THREAD

**Issue by cinek810** [irods/irods_resource_plugin_s3#1903]
We're seeing multiple errors (happening randomly) during massive s3 upload. The error messages looks like:
```
Oct 15 11:09:30 pid:3423 remote addresses: 10.214.44.11 ERROR: [-]      /tmp/tmp919rQK/s3/libirods_s3.cpp:1746:irods::error s3StartOperation(irods::plugin_property_map &) :  status [SYS_CONFIG_FILE_ERR]  errno [] -- message [Unknown error in authorization file.]
        [-]     /tmp/tmp919rQK/s3/libirods_s3.cpp:483:irods::error s3ReadAuthInfo(irods::plugin_property_map &) :  status [SYS_CONFIG_FILE_ERR]  errno [] -- message [Unknown error in authorization file.]
                [-]     /tmp/tmp919rQK/s3/libirods_s3.cpp:458:irods::error readS3AuthInfo(const std::string &, std::string &, std::string &) :  status [SYS_CONFIG_FILE_ERR]  errno [] -- message [Unknown error in authorization file.]

Oct 15 11:09:48 pid:3504 remote addresses: 10.214.44.11 ERROR: [-]      /tmp/tmp919rQK/s3/libirods_s3.cpp:1746:irods::error s3StartOperation(irods::plugin_property_map &) :  status [SYS_CONFIG_FILE_ERR]  errno [] -- message [Unknown error in authorization file.]
        [-]     /tmp/tmp919rQK/s3/libirods_s3.cpp:483:irods::error s3ReadAuthInfo(irods::plugin_property_map &) :  status [SYS_CONFIG_FILE_ERR]  errno [] -- message [Unknown error in authorization file.]
                [-]     /tmp/tmp919rQK/s3/libirods_s3.cpp:458:irods::error readS3AuthInfo(const std::string &, std::string &, std::string &) :  status [SYS_CONFIG_FILE_ERR]  errno [] -- message [Unknown error in authorization file.]
```

I took a look into the code and I can't figure out how this can happen, it looks like it's comming from libirods_s3.cpp:
```
    if ((result = ASSERT_ERROR(fptr != NULL, SYS_CONFIG_FILE_ERR, "Failed to open S3 auth file: \"%s\", errno = \"%s\".",
                               _filename.c_str(), strerror(errno))).ok()) {
#CODE REMOVED
        return result;
    }

    result = ERROR( SYS_CONFIG_FILE_ERR, "Unknown error in authorization file." );
```
so the only option to go to "Unknown error in authorization file" line (it was recently updated but logic wasn't changed) is to get ASSER_ERROR returning an error object with status true, which as far as I understand can't happen as a result of ASSERT_ERROR without it's own error message being displayed.

**Comment by trel** [comment]
I saw this recently when the configured S3 keypair file didn't exist?

**Comment by cinek810** [comment]
but.. in this case we should also see:  ```Failed to open S3 auth file: %s``` right before the ```Unknown error...```?

It works for the majority of requests, so the file is there :) It only fails from time to time on the production server that's not touched at all.

**Comment by JustinKyleJames** [comment]
I believe you are correct that the error is at the line "Failed to open S3 auth file" due to the fptr being NULL.  

It is unfortunate that we don't return that error directly but instead return the "Unknown error in authorization file" error.  The only way we can get down to that return is if we had the previously mentioned error which is more specific.

I will take a look and see why that fptr could be null at this point.

https://github.com/irods/irods_resource_plugin_s3/blob/5b7fa3f3cf373900828454147226a225791e97a5/s3/libirods_s3.cpp#L493-L520

**Comment by JustinKyleJames** [comment]
Are you running cacheless or cache version of S3?

**Comment by JustinKyleJames** [comment]
I am going to fix the stomping of the original error in this issue.  That should then give us a lot more information about what happened.

**Comment by cinek810** [comment]
We see this on a compound resource. I agree that getting the errno from fopen may help to resolve/understand it.
