### ISSUE TITLE
4.2.8 does not use latest libs3

### ISSUE THREAD

**Issue by murlock** [irods/irods_resource_plugin_s3#1929]
- [x] master
- [x] 4-2-stable
- [x] 4-2-8-stable
-----

Hi,

Last year, I've submitted this PR (https://github.com/irods/libs3/pull/2),
but the `irods-resource-plugin-s3` still depends on `irods-externals-libs3a30e55e8-1` instead of `irods-externals-libs359b62371-0`

Is it possible to update dependency for next release ?

**Comment by trel** [comment]
Yes, this was an oversight... we started the process, created the new externals package... 

https://github.com/irods/externals/commit/e81c8ee63e04bb173b9592733090944c3def9d27#diff-1b1ba5594d5bdffa6ee955bbfcfd2702

and then hit a snag with `-Wunused-function` appearing in our builds.

We released with this tweak to span our old and new target OSs and their varying versions of openssl.

https://github.com/irods/irods_resource_plugin_s3/blob/bbd101ba94cad3e62a9f7de5bee32f498491e35c/CMakeLists.txt#L52

Yes, we'll get this bumped.

**Comment by murlock** [comment]
Thanks for the update :)

**Comment by trel** [comment]
The plugin will use the latest rebased-atop-bji irods/libs3 and be released as 4.2.8.1 as well as 4.2.9.0 with iRODS 4.2.9.

**Comment by trel** [comment]
opening again for 4.2.8.1 coming soon.

**Comment by murlock** [comment]
Thanks for this release !
