### ISSUE TITLE
Handle a not found when a HEAD request returns not found immediately after an upload

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/irods_resource_plugin_s3#1931]
* [x]  master
* [x]  4-2-stable
-----

I have noticed with Amazon S3 that every so often on an upload the HEAD request will return a not found HTTP response.  If something is done in iRODS on that object immediately after the PUT it is possible that that action may trigger a stat which calls HEAD which will fail.

To resolve this, after an upload is finished do a HEAD and repeat with a slight delay if it returns a not found.

Note:  Normal calls to s3_file_stat_operation() can't repeat on the HEAD call when not found is encountered because it is often the case that that this is the proper and expected behavior.  We should only repeat in this one instance when we know the object should exist.

**Comment by JustinKyleJames** [comment]
Note the following from AWS documentation:

 

> For example, if you PUT an object in Amazon S3 and then immediately make a HEAD or GET request for that object, you might get a "Not Found" error. To resolve these errors, enable EMRFS consistent view. For more information, see Consistent View.

**Comment by trel** [comment]
Also note we will not be requiring the enabling of `EMRFS consistent view` since we need to be compliant with many different vendors' implementations of the S3 protocol.  Hence the HEAD (with retry logic) just after a PUT completes.  This should be vendor agnostic and provide reliable behavior.

**Comment by JustinKyleJames** [comment]
This has been merged to the master branch and tested.  Closing this issue.
