### ISSUE TITLE
Implement decoupled naming in streaming mode

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/irods_resource_plugin_s3#1940]
- [x] master
- [x] 4-2-stable
-----

**Comment by JustinKyleJames** [comment]
Implement decoupled naming in streaming mode

**Comment by JustinKyleJames** [comment]
This has been fixed with the S3 streaming which is now merged.

**Comment by trel** [comment]
This was included in https://github.com/irods/irods_resource_plugin_s3/commit/8ecb1b34e1fa60e6c02314502e5230e23b9bd9e5 on 4-2-stable.

**Comment by JustinKyleJames** [comment]
This has been merged to the master branch and tested.  Closing this issue.
