### ISSUE TITLE
Implement MPU disabled flag in streaming mode

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/irods_resource_plugin_s3#1941]
* [x]  master
* [x]  4-2-stable
-----

Implement MPU disabled flag in streaming mode

1. Does this make sense?
2. If we do implement this, we will have to use the cache file and then stream the cache file at the end.

**Comment by trel** [comment]
Unclear this is used/needed by anyone today.

Let's let community interest/demand drive this issue.

**Comment by JustinKyleJames** [comment]
This has been merged to the master branch and tested.  Closing this issue.
