### ISSUE TITLE
Support Amazon S3 glacier API extensions

### ISSUE THREAD

**Issue by anderbubble** [irods/irods_resource_plugin_s3#1959]
The iRODS s3 resource plugin should be enhanced to support the S3 glacier extensions.

https://docs.aws.amazon.com/amazonglacier/latest/dev/amazon-glacier-api.html

This support would allow iRODS to manage collections that are stored in low-cost archival mediums, including on-prem storage that supports the s3 glacier extensions. (For example, we are looking at FUJIFILM Object Archive.)

- Movement of data between the remote archival storage and the remote cache storage should have a configurable timeout to distinguish asynchronous access from synchronous access. That is, iRODS should be able to either block until the data is made available, or return a predictable status code and message to indicate that the requested data is being asynchronously retrieved.
- File-system-like client interfaces will need to be tested in both async and sync scenarios, including NFSRODS and DAVRODS.

**Comment by JustinKyleJames** [comment]
This has been implemented in both the 4-2-stable and master branches.

**Comment by anderbubble** [comment]
Great! Thanks, @JustinKyleJames!
