### ISSUE TITLE
minio-py 7.0.x not compatible with current test suite

### ISSUE THREAD

**Issue by alanking** [irods/irods_resource_plugin_s3#1963]
- [x] master
- [x] 4-2-stable
---
The latest major version of `minio-py` is not compatible with the test suites. Identified issues include:
 - Removal of `ResponseError` object from `minio.errors` module
 - Use of `urllib.parse` (introduced in python3, which is not currently supported in the test-running script)

There may be more, but this is what I saw when trying to run the test suite through CI

**Comment by JustinKyleJames** [comment]
This has been merged to master.  It can be closed.
