### ISSUE TITLE
Adjust irepl overwrite/update tests to expect error messages

### ISSUE THREAD

**Issue by alanking** [irods/irods_resource_plugin_s3#1965]
- [x] master
- [x] 4-2-stable
---
The following 3 tests are failing due to some behavioral changes in the replication API in the server:
  - test_irepl_over_existing_second_replica__ticket_1705
  - test_irepl_over_existing_third_replica__ticket_1705
  - test_irepl_update_replicas

These tests should be adjusted as was done in this commit in irods/irods: https://github.com/irods/irods/commit/2f1b1dbe7f621554f4f7fbd12a77ba144f312e50#diff-11e18b971bfeed0f097be79b877dbaff8e1e483f72628e09c90438c352710e91

**Comment by JustinKyleJames** [comment]
The current test cases have the updated with the necessary changes.  This can be closed.
