### ISSUE TITLE
Fix codacy issues found in pull requests.

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/irods_resource_plugin_s3#1976]
- [ ] master
- [x] 4-2-stable
-----

This is a placeholder for codacy fixes found during pull requests.

**Comment by trel** [comment]
this shouldn't be a long-standing issue on its own.    we should describe each bug separately if they're found later... and fix them with any new code going in... when the new code goes in.

please close this once we get s3 streaming merged into master.

**Comment by JustinKyleJames** [comment]
This has been merged to the master branch and tested.  Closing this issue.
