### ISSUE TITLE
missing dependencies while build from source code in centos7

### ISSUE THREAD

**Issue by peggy0135** [irods/irods_resource_plugin_s3#1989]
I was trying to build and install from source code.
But when I finished generating the "irods-resource-plugin-s3-4.2.9.1-1.x86_64.rpm" and tried to install with it.
It showed the message below:
[root@centos7 irods_resource_plugin_s3]# rpm -i irods-resource-plugin-s3-4.2.9.1-1.x86_64.rpm 
error: Failed dependencies:
	irods-externals-libarchive3.3.2-1 is needed by irods-resource-plugin-s3-4.2.9.1-1.x86_64
	irods-externals-avro1.9.0-0 is needed by irods-resource-plugin-s3-4.2.9.1-1.x86_64
	irods-externals-boost1.67.0-0 is needed by irods-resource-plugin-s3-4.2.9.1-1.x86_64
	irods-externals-clang-runtime6.0-0 is needed by irods-resource-plugin-s3-4.2.9.1-1.x86_64
	irods-externals-zeromq4-14.1.6-0 is needed by irods-resource-plugin-s3-4.2.9.1-1.x86_64
	irods-externals-json3.7.3-0 is needed by irods-resource-plugin-s3-4.2.9.1-1.x86_64
	irods-externals-catch22.3.0-0 is needed by irods-resource-plugin-s3-4.2.9.1-1.x86_64
	irods-externals-nanodbc2.13.0-1 is needed by irods-resource-plugin-s3-4.2.9.1-1.x86_64
	irods-externals-fmt6.1.2-1 is needed by irods-resource-plugin-s3-4.2.9.1-1.x86_64
	irods-runtime = 4.2.9 is needed by irods-resource-plugin-s3-4.2.9.1-1.x86_64

then I find out the packages in irods-externals except "irods-runtime"
is there any way that I build the package "irods-runtime" from source code.
Thank you.

**Comment by trel** [comment]
The irods-runtime package comes from building the main irods repository (same as irods-devel).

**Comment by peggy0135** [comment]
sorry, any hint where it may be in the directory?
Thank you

**Comment by trel** [comment]
Excellent - please update here if there is any action needed in this s3 plugin repository.

**Comment by peggy0135** [comment]
I finished installing the s3 plugin with source code on centos7.
But I faced another problem while porting on centos8
I installed python but when I install the irods-runtime rpm, it just keep showed me the error message:

[root@localhost ~]# rpm -i irods-runtime-4.2.9-1.x86_64.rpm 
error: Failed dependencies:
	python is needed by irods-runtime-4.2.9-1.x86_64
	python-psutil is needed by irods-runtime-4.2.9-1.x86_64
	python-requests is needed by irods-runtime-4.2.9-1.x86_64
	python-jsonschema is needed by irods-runtime-4.2.9-1.x86_64

even I install them with rpm files manually
what reason would cause the problem?
Thank you.

**Comment by trel** [comment]
Yes, you need those other packages installed - they are dependencies of the irods-runtime package itself.

If you install the `epel-release` package, it will provide an additional yum repository which hosts some of the required packages.

**Comment by peggy0135** [comment]
I agree with that, but after I tried to install the packages manually.
It still showed that:
[root@localhost build]# rpm -i irods-runtime-4.2.9-1.x86_64.rpm 
error: Failed dependencies:
	python is needed by irods-runtime-4.2.9-1.x86_64
	python-psutil is needed by irods-runtime-4.2.9-1.x86_64
	python-requests is needed by irods-runtime-4.2.9-1.x86_64

It looks like something can not recognize some of the packages I installed.
Is there anything that I should mention about (centos7 vs centos8)
Thank you

**Comment by trel** [comment]
Ah, I believe the packages now have `python3` as their prefix in CentOS8.

We have not yet released packages confirmed to work on CentOS8, and the EOL of Python2 is one of the reasons.

You can change the dependencies yourself to get things to install, but we have not yet tested all the scripts in Python3.
