### ISSUE TITLE
Missing file test_irods_resource_plugin_s3_gcs.py referenced in CMakeLists.txt in 4-2-stable

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods_resource_plugin_s3#2000]
- [x] master
- [x] 4-2-stable
------
`packaging/test_irods_resource_plugin_s3_gcs.py` was added to the `install` call in `CMakeLists.txt`:
https://github.com/irods/irods_resource_plugin_s3/commit/5ad3da14d89fa0ace8379c34d2c989ad60156ae4#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR112

This file does not exist in the repository.

**Comment by alanking** [comment]
I think we should remove it unless there is an implementation out there somewhere. This is blocking the 4.2.11.0 release.

**Comment by trel** [comment]
I think your fix is correct... google cloud storage/platform is tested with this file instead... https://github.com/irods/irods_resource_plugin_s3/blob/master/packaging/test_irods_resource_plugin_s3_for_gcp.py

@JustinKyleJames ... does this assessment seem correct?

**Comment by alanking** [comment]
This can be closed, I think.
