### ISSUE TITLE
Catch boost::interprocess:bad_alloc instead of std::bad_alloc

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/irods_resource_plugin_s3#2033]
- [ ] master
- [ ] 4-2-stable
-----

Catch boost::interprocess:bad_alloc instead of std::bad_alloc when doing allocations in the interprocess shared memory.

**Comment by JustinKyleJames** [comment]
This is actually covered in another issue so closing this one.

**Comment by trel** [comment]
which issue?   please link to it so we don't leave dead ends for the next reader.

**Comment by JustinKyleJames** [comment]
> which issue? please link to it so we don't leave dead ends for the next reader.

This is in the commit for issue #2024.

**Comment by trel** [comment]
Gotcha - thanks.
