### ISSUE TITLE
Investigate `USING_JSON` macro

### ISSUE THREAD

**Issue by alanking** [irods/irods_resource_plugin_s3#2037]
- [x] main
- [x] 4-2-stable
---
https://github.com/irods/irods_resource_plugin_s3/blob/9cdae5121d8d409fc2d8d386cb3064b1e4effaa2/s3/libirods_s3.cpp#L17-L19

See if the `USING_JSON` macro can be removed

**Comment by JustinKyleJames** [comment]
This is legacy code.  I do not see that defined anywhere in the code or used in a -D flag.  I am guessing it can be removed.   I will test.

**Comment by alanking** [comment]
We did it
