### ISSUE TITLE
Standardize the configuration setting names - *_SEC vs *_SECONDS

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/irods_resource_plugin_s3#2044]
This is for 4.3.  I propose that for backwards compatibility we allow either for the ones that are currently *_SEC.  First, look for the *_SECONDS.  If it doesn't exist, look for the *_SEC.  If neither exist then use the default.

**Comment by korydraughn** [comment]
Yes. We can slowly migrate users from the old variable names by marking them deprecated. Then in a later release, we remove them and support the standardized names.

**Comment by JustinKyleJames** [comment]
This code has been merged with the main branch.  Closing this issue.
