### ISSUE TITLE
Incorrect stream open mode when O_CREAT and O_APPEND are set

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/irods_resource_plugin_s3#2079]
- [x] main
- [x] 4-2-stable
-----

We have to translate POSIX open modes to stream open modes.

During testing I noticed that O_CREAT should translate to the ios_base::trunc flag being set.  

However, if the O_APPEND flag is also set, that results in both ios_base::app and ios_base::trunc being set which causes open() to fail.  Therefore, if O_CREAT and O_APPEND is set, the ios_base::trunc flag should be disabled.

**Comment by alanking** [comment]
@JustinKyleJames - Please checkbox and close if completed. Thanks

**Comment by JustinKyleJames** [comment]
Closing
