### ISSUE TITLE
Detached mode causes resource server failure when resource host set to catalog provider

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/irods_resource_plugin_s3#2082]
- [x] master
- [ ] 4-2-stable
-----

### Summary

Detached mode as it is currently implemented causes the following issues:

1.  If the host of the detached resource is the catalog provider, the consumer will fail to start.
2.  If the resource host is a catalog consumer and there are other attached resources on this consumer, this makes the local server believe it owns the resource which would cause the following problems:
- A put on the local server to this attached resource will incorrectly place the vault file on the local filesystem.
- A get on the local server to this attached resource will try to read the file from the vault on the local filesystem.

### Background

To implement detached mode, we read the RESOURCE_HOST entry (a rodsServerHost_t) from the resource property map.  If detached mode was enabled, the localFlag for this entry was set to LOCAL_HOST.

The problem with this is that this rodsServerHost_t entry is not owned by the resource structure.  It is shared throughout the code.  That rodsServerHost_t entry is often for a different server but we are tricking the local server into thinking that it is local.  While that works for the purposes of detached mode, it confuses the server in other parts of the code.

That causes the most noticeable error when the the host is set to the catalog provider.  The resource code will set the localFlag making the code believe that it is the catalog provider.  However, the code knows it is not the catalog provider so it detects an invalid configuration and does not start properly.

### Workaround

The preferred workaround is to disable detached mode.

The other workaround is to set the resource host to something that is not the catalog provider and has no additional resources.

### Required fix

Rather than setting the localFlag on the rodsServerHost_t entry returned by looking up the RESOURCE_HOST key in the resource property map, look up the rodsServerHost_t entry for the current server and set this into the RESOURCE_HOST key in the resource property map.

**Comment by alanking** [comment]
Please checkbox and close if finished. Thanks!

**Comment by JustinKyleJames** [comment]
This fix has been merged.
