### ISSUE TITLE
Uploading very large files from cache can trigger part upload timeouts

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/irods_resource_plugin_s3#2117]
- [x] main
- [x] 4-2-stable
---

The S3_MAX_UPLOAD_SIZE configuration setting was created to represent the part size upper limit for the S3 provider.  For Amazon, this is 5 GiB.

This parameter is also used when determining the part sizes when flushing a very large file from a local cache file after a redirect.

One problem I've seen in my network is that if I keep this as the default of 5 GiB, I often run into the 2 minute timeout in Amazon for uploading parts.

The current workaround is to set the S3_MAX_UPLOAD_SIZE to something smaller than 5 GiB.  With the 5 TiB object size limit and 10,000 maximum number of parts per multipart upload, this can be set to a lower value without compromising the maximum object size that can be uploaded.

After discussion we have decided to fix this as follows:

1. Initially set the part size to min(S3_MAX_UPLOAD_SIZE, file_size / number of transfer threads).
2. If a part fails due to a timeout, note that this happened in the logs, halve the part size and try again.

Users can use this information in the logs to lower the S3_MAX_UPLOAD_SIZE.

**Comment by trel** [comment]
is adding 'PART' even better?    unless is it somehow misleading?

`S3_MAX_UPLOAD_PART_SIZE_MB`

**Comment by trel** [comment]
right - definitely have to catch backwards compatibility.

**Comment by JustinKyleJames** [comment]
We decided to not change the name to include "PART" because this is used in other areas to determine whether or not to use the non-multipart upload API or the multipart upload API.

With the changes in #2119, the part sizes when flushing a cache file is no longer tied to this configuration setting.  The S3_MAX_UPLOAD_SIZE_MB should remain the actual maximum part size imposed by the S3 vendor.

**Comment by alanking** [comment]
@JustinKyleJames - Please close if complete. Thanks!

**Comment by JustinKyleJames** [comment]
Closing
