### ISSUE TITLE
Deprecate S3_MAX_UPLOAD_SIZE in favor of S3_MAX_UPLOAD_SIZE_MB

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/irods_resource_plugin_s3#2118]
- [x] main
- [x] 4-2-stable
---

I have found that the units for the S3_MAX_UPLOAD_SIZE is not obvious.  The default value for this is 5 GiB which requires a setting of 5 * 1024 (MiB).

I have to look this up every time I adjust it so I can't imagine that this is obvious to others.

I am going to deprecate S3_MAX_UPLOAD_SIZE in favor of S3_MAX_UPLOAD_SIZE_MB.  Both will still work although the former will give a deprecation warning.

**Comment by trel** [comment]
[consider `S3_MAX_UPLOAD_PART_SIZE_MB`](https://github.com/irods/irods_resource_plugin_s3/issues/2117#issuecomment-1546429508)

**Comment by JustinKyleJames** [comment]
> [consider `S3_MAX_UPLOAD_PART_SIZE_MB`](https://github.com/irods/irods_resource_plugin_s3/issues/2117#issuecomment-1546429508)

The legacy/cache code uses this setting for decisions about single part copies and uploads.

There is another setting called S3_MPU_CHUNK.  This is actually a better setting to use when making decisions on flushing the cache file when in streaming mode.

By doing this, we don't have to alter the setting that is intended to represent the limit set by the S3 provider.

I suggest the following:

1.  In addition to changing the name of the S3_MAX_UPLOAD_SIZE to S3_MAX_UPLOAD_SIZE_MB, change S3_MPU_CHUNK to S3_MPU_CHUNK_MB.  (Should we consider a more extensive rename?)

2.  Change the streaming with a cache file code to use this S3_MPU_CHUNK_MB rather than S3_MAX_UPLOAD_SIZE_MB.

**Comment by JustinKyleJames** [comment]
> Agreed the chunk setting seems more appropriate.
> 
> I think both 1 and 2 make sense.

I am going to have to correct myself.  That S3_MPU_CHUNK is used as a lower bound of the part size and for legacy operation to determine if multipart is being used.  That isn't a good setting to use either.

I suggest adding a new setting called S3_MPU_PREFERRED_PART_SIZE_MB or something like that.

**Comment by trel** [comment]
so... for chunking...

- for the minimum/detection... "S3_MPU_CHUNK" -> "S3_MPU_MIN_CHUNK_SIZE_MB"
- for the maximum... a new setting... "S3_MPU_MAX_CHUNK_SIZE_MB"

--

and for the entire file... `S3_MAX_UPLOAD_SIZE_MB` ?

**Comment by alanking** [comment]
@JustinKyleJames - Please close if complete. Thanks!

**Comment by JustinKyleJames** [comment]
Closing
