### ISSUE TITLE
Lower the default part size when flushing a file from cache.

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/irods_resource_plugin_s3#2119]
- [x] main
- [x] 4-2-stable
---

This will go along with issue #2117.  Now that issue #2114 has been fixed, it makes sense to start with smaller part sizes when flushing a cache file to S3.  This would have the following benefits:

1. If a part upload fails, using smaller parts would be allow quicker retries.
2. When you run into the issue described in #2117, the upload can be time consuming as you may have to attempt the large file flush multiple times before you get to a part size that is small enough to not trigger the 2 minute timeout imposed by AWS.

The only drawback is that more part headers will be sent but that isn't significant compared to the amount of data sent.

Also note that even if the upper limit on the part size was set to 1 GiB, you would still be able to upload the largest file possible (5 TiB) within the 10,000 part limit.

**Comment by trel** [comment]
This seems correct/good.   Additional headers are insignificant.

New default part size would be 1GB, down from 5GB.

**Comment by alanking** [comment]
@JustinKyleJames - Please close if complete. Thanks!

**Comment by JustinKyleJames** [comment]
Closing
