### ISSUE TITLE
Test with invalid keys periodically test_iput_with_invalid_secret_key_and_overwrite__issue_6154

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/irods_resource_plugin_s3#2121]
- [x] main
- [x] 4-2-stable
---

The test `test_iput_with_invalid_secret_key_and_overwrite__issue_6154` is periodically failing.  If we put a small sleep (1-2 seconds) after fixing the secret key it passes consistently.

This needs to be investigated more.  As a work-around we will add in the sleep.

**Comment by alanking** [comment]
@JustinKyleJames - Please close if complete. Thanks!

**Comment by JustinKyleJames** [comment]
Closing
