### ISSUE TITLE
Replication to S3 resource with checksums enabled causes errors

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/irods_resource_plugin_s3#2122]
- [x] main
- [x] 4-2-stable
---

This was tested in 4.2.12.  When I put a file on a unixfilesystem resource with the -k option and then attempted to replicate to an S3 resource, I got the following error:

```
Level 0: [-]    /irods_resource_plugin_s3/s3/s3_operations.cpp:532:std::tuple<irods::error, std::shared_ptr<dstream>, std::shared_ptr<s3_transport> > irods_s3::make_dstream(irods::plugin_context &, const std::string &) :  status [SYS_INTERNAL_ERR]  errno [] -- message [Replicating from source to destination but was not able to find the replication destination in L1desc table.]
        [-]     /irods_resource_plugin_s3/s3/s3_operations.cpp:301:irods::error irods_s3::get_number_of_threads_data_size_and_opr_type(irods::plugin_context &, int &, int64_t &, int &, bool) :  status [SYS_INTERNAL_ERR]  errno [] -- message [Replicating from source to destination but was not able to find the replication destination in L1desc table.]
```

I got this error in both attached and detached mode although others got the error only in detached mode.

**Comment by trel** [comment]
This is sufficient to see this error?

```
$ iput -k -R ufs0 file0
$ irepl -R s3resc file0
```

**Comment by JustinKyleJames** [comment]
> This is sufficient to see this error?
> 
> ```
> $ iput -k -R ufs0 file0
> $ irepl -R s3resc file0
> ```

yes

**Comment by trel** [comment]
okay good - easy enough to get a test in.

**Comment by alanking** [comment]
Tagging @JonathanMELIUS just in case this is interesting...

**Comment by JustinKyleJames** [comment]
I have a fix for this but the updated test seems to be failing when you disable multipart uploads.  I will need to look further into that.

I might consider fixing this and writing a more targeted issue for this issue with multipart disabled.  That is not a normal setting that most people use.  I believe it was created for GCS when it did not support multipart.  I don't want to hold up this fix it if would be helpful for the community.

**Comment by trel** [comment]
that seems reasonable - solve for this first.   if the other seems complicated, we can talk about getting a release out before a fix for that is available.   but.. hopefully, you can identify and fix the disabled multipart scenario as well.

**Comment by JustinKyleJames** [comment]
closing
