### ISSUE TITLE
Writing a file > 32 MiB with checksum to S3 with MPU disabled fails

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/irods_resource_plugin_s3#2124]
- [x] main
- [x] 4-2-stable
---
Writing a file > 32 MiB with checksum to S3 with MPU disabled fails.

The following is the sequence of events:

1. File is streamed from multiple threads.
2. Since MPU is disabled this forces the use of a cache file since random writes are not allowed in S3.
3. When the file write is done the object is closed.  At this point the cache file is flushed to S3.
4. The object is re-opened for the read to calculate the checksum.
5. The oprType remains PUT_OPR.
6. The plugin thinks that this is another full file write so doesn't read the file back into cache.
7. Seeks are reads are called which fail due to the cache file not being staged from S3.

The key is that the oprType remains PUT_OPR even though we have moved to a read-only mode.

I am searching for a way to determine that we are in the scenario where we can determine that we are doing a read-only operation and that a cache file is not needed.

**Comment by alanking** [comment]
@JustinKyleJames - Please close if complete. Thanks!

**Comment by JustinKyleJames** [comment]
Closing
