### ISSUE TITLE
Need to change references to irods::file_object::size to rodsLong_t (aka long long)

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/irods_resource_plugin_s3#2128]
- [x] main
---

This was changed from size_t to rodsLong_t in a recent push to iRODS and needs to be changed in the plugin as it moved from unsigned to signed.

**Comment by alanking** [comment]
See irods/irods#7154 and irods/irods#7160 for details.

**Comment by alanking** [comment]
@JustinKyleJames - Please checkbox and close. Thanks!
