### ISSUE TITLE
Absorb libs3

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods_resource_plugin_s3#2138]
- [x] relicense plugin
- [x] absorb libs3
- [x] remove libs3 from externals
- [x] archive libs3 fork

-------

Given that upstream libs3 is no longer maintained, it may be a good idea to absorb the parts we use into the plugin itself, and eliminate the dependency.

Potential hurdle: libs3 is published under LGPLv3

**Comment by trel** [comment]
This agrees with my initial thoughts... the hurdle is real.

https://opensource.stackexchange.com/a/6701

**Comment by SwooshyCueb** [comment]
We could relicense the resource plugin as LGPLv3

**Comment by trel** [comment]
Ah, very true.   Probably the way forward.

**Comment by SwooshyCueb** [comment]
How are we feeling on this? It sure would be nice to be rid of another externals package.

**Comment by korydraughn** [comment]
If there's no licensing issues, let's do it.

I think the s3 resource plugin is the only project using libs3 so it makes sense to me.

**Comment by SwooshyCueb** [comment]
As long as we re-license the plugin to LGPLv3, there are no licensing issues

**Comment by trel** [comment]
I think we can relicense the s3 resource plugin.

We are not aware of any downstream re-packagers of this plugin that we would need to confer/discuss with or inform and dynamically linking / loading this plugin does not cause any burden to the iRODS server itself.

Let's prepare a PR against this issue to see what that looks like.

**Comment by SwooshyCueb** [comment]
Once our libs3 fork has been archived, this issue can be closed

**Comment by alanking** [comment]
https://github.com/irods/libs3 now has 0 open issues. Are we ready to archive?

**Comment by trel** [comment]
Ooh, I believe we are.   Need to add a last commit and point the reader elsewhere at the top of the README...

**Comment by alanking** [comment]
irods/libs3 has now been archived. @SwooshyCueb - Anything left to do for this?

**Comment by SwooshyCueb** [comment]
Not that I can think of!
