### ISSUE TITLE
Non-deterministic build failure when building libs3

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods_resource_plugin_s3#2156]
When building a debug build of the plugin post-#2152, the compiler sometimes crashes when building libs3 due to a bug in clang 13.0.0. The current workaround is to just retry the build until it succeeds. This bug does not occur when using a newer version of clang. We do not currently have plans to bump the version of clang that we provide.

**Comment by trel** [comment]
Specifically... clang 13.0.1 appears to have fixed it.

We think it might be https://github.com/llvm/llvm-project/commit/67b5bc26bde81a60688ae5c049a001ffbc6dd614 (one of the [79 commits since 13.0.0](https://github.com/llvm/llvm-project/compare/llvmorg-13.0.0...llvmorg-13.0.1))

**Comment by trel** [comment]
crash can be seen here... https://github.com/irods/irods_resource_plugin_s3/pull/2152#issuecomment-1856187018

**Comment by trel** [comment]
oh, a twist!

**Comment by trel** [comment]
and the crash is the 'same'?

**Comment by SwooshyCueb** [comment]
Seems to be.

Here's the output and the dumped files from a crash I just observed:
https://gist.github.com/SwooshyCueb/d90275f4047fe5ed73c8a5c85eac233d

**Comment by SwooshyCueb** [comment]
I wrote a script to compile the source files and headers over and over again until the compiler crashed, and found that only three files cause crashes:
- `bucket.c`
- `multipart.c`
- `request.c`

After some testing with `-Weverything`, I identified that these three files, and no others, would throw the `-Wvla` warning, and sure enough, if I swap the variable length array declarations for calls to `alloca`, the compiler crashes go away.

I'll submit a PR shortly.

**Comment by trel** [comment]
Great stuff.
