### ISSUE TITLE
Investigate `iget` of replica with different naming scheme from host resource

### ISSUE THREAD

**Issue by alanking** [irods/irods_resource_plugin_s3#2161]
- [x] main
- [x] 4-2-stable
---
1. put an object while resource is using consistent naming scheme; update naming scheme to decoupled; get the object
2. put an object while resource is using decoupled naming scheme; update naming scheme to consistent; get the object

Can it get the object? Do we expect it to be able to get the object?

_Originally posted by @alanking in https://github.com/irods/irods_resource_plugin_s3/pull/2159#discussion_r1445139808_
            
---

Please investigate and consider adding a test whether it works or not.

**Comment by JustinKyleJames** [comment]
I committed an update to the test cases I previously wrote for pull #2159.

Basically, I was doing the following:

1. Set the ARCHIVE_NAMING_POLICY.
2. Put a file.
3. Update ARCHIVE_NAMING_POLICY
4. Overwrite the file
5. Get and verify the file.

I added a get and verify step between 3 and 4.  That should address this issue.

**Comment by trel** [comment]
so to answer the original question - yes, we do expect it to work, and have now demonstrated it working.

for both cases 1 and 2.

**Comment by JustinKyleJames** [comment]
The commit with this has been merged to both main and 4-2-stable.  Closing this issue.
