### ISSUE TITLE
On CompleteMultipartUpload, put a timer on the wait for threads to complete the streaming of their part.

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/irods_resource_plugin_s3#2179]
Currently in CompleteMultipartUpload, multiple background threads are used to read each individual part and write it to the object in iRODS (at the specified offset).

If for some reason one thread never completes, the main thread will wait forever.  We should put some type of timeout on this and error out if we encounter the timeout.

**Comment by JustinKyleJames** [comment]
This was meant for the S3 API.  Closing this.

**Comment by trel** [comment]
we can transfer issues, rather than closing and reopening.  just for future knowledge...
