### ISSUE TITLE
Many tests need to be updated to expect new deprecation warning "Specifying a minimum number of replicas to keep is deprecated."

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods_resource_plugin_s3#2183]
A new deprecation warning was introduced with irods/irods#7502, and the tests that pass `--purgec` to an icommand need to be updated to expect this warning.

**Comment by alanking** [comment]
This commit updated many of the tests to expect this message in 4-2-stable: 9d2e456871e94f5f01f3e8fc0ac8e599b2fef583 Others have probably occurred since then, but... it's a start.
