### ISSUE TITLE
Streaming multiple files with the iput N flag > 1 fails.

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/irods_resource_plugin_s3#2198]
- [x] 4-2-stable
- [x] 4-3-stable
- [x] main
---
Streaming multiple files with the iput N flag > 1 fails.

This might be related to #2197 although this appears to happen with 4.2.x as well so it might be slightly different.

I have verified this for 4.3.2.

**Comment by JustinKyleJames** [comment]
I believe this is related to #2197 but will leave both open.

This happens when iRODS doesn't use as many threads as expected because the -N option is not being honored.  Most likely this is because the file size is small.

When files are sufficiently large enough so that the -N flag is honored, everything passes.

Because the number of threads needing to close are stored in shared memory (due to requirements to support multiprocess writes via istream) this will pass periodically as the number of expected close counter reaches zero.  For example, if you put a very small file with -N2, it will pass every other time you try to put that same file.

**Comment by JustinKyleJames** [comment]
I have closed #2197 as this has the same root cause as that one.  I am just using this one to track the changes.

**Comment by alanking** [comment]
@JustinKyleJames - Please checkbox and close if complete. Thanks!

**Comment by JustinKyleJames** [comment]
Closing.
