### ISSUE TITLE
irsync with checksum when writing to S3 fails

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/irods_resource_plugin_s3#2204]
- [x] 4-2-stable
- [x] 4-3-stable
- [x] main
---

The irsync operation when writing to an S3 resource is failing when the checksum flag in enabled.

There are two parts to this:

1. The check on line 336 below which was added to support PRC transfers, seems to not work for irsync.  When `oprType == COPY_DEST` it appears that I do need to get the number of threads from `getNumThreads()`.  When I remove the check for COPY_DEST, the number of threads is correct.  **Whether this breaks transfers via PRC is an open question.**

https://github.com/irods/irods_resource_plugin_s3/blob/f3e68506631f2db3f975235d344857d5b5c37025/s3_resource/src/s3_operations.cpp#L336-L346

2. After fixing the first part, I noticed that the read-after-write for checksum calculation is showing that there are four threads expected.  However, this only does one open, a bunch of reads, and one close.  This leaves the shared memory for that object with a `threads_remaining_to_close` counter of 3 once the reads are done.  If the destination file is removed and another irsync is performed quickly after the first, it will fail this second time because of the inconsistent state in shared memory.  In addition, this causes the shared memory for this object to not be cleaned up.  The shared memory will timeout after 180 seconds so at that point it will work again as the shared memory data will be reset.

Unfortunately, at the point of line 336, it is impossible to tell the difference between the irsync copy and the irsync read-after-write for checksum.  (The open flags are identical.)  By the time we get into the transport code, we can tell that we are doing a read-only operation.  For read-only operations, we do not need to know the number of threads.  We can simply rely on the file open counter.  Therefore, in the transport constructor I will set the `number_of_client_transfer_threads` to the unknown value of -1.  That seems to make everything work.

Note:  The reason we can't rely of the file open counter for writes is because multiple threads can open/write/close before one thread does the open.  This would break in cases we need to do post-write processing like flushing a cache file or completing multipart.  This is not a concern on reads.

**Comment by JustinKyleJames** [comment]
To add to the note above, there are two different ways we know we are done.

1. Use the `number_of_client_transfer_threads` we determined from iRODS.  This isn't straight forward as this information isn't directly provided, sometimes missing, etc.  Then count down when we have open/closes.
2. Use a separate counter which tracks opens and closes.

The second option is problematic for writes because of order issues.  The counter can go to zero before we are truly done.  This option is fine for reads.

The first option works well if we actually can get the true number of transfer threads.  Getting that number has been an issue.

**Comment by JustinKyleJames** [comment]
See issue #1977 for why the above change was made.

**Comment by JustinKyleJames** [comment]
I traced through the code changes with git blame and the test for oprType from above was not done for the change to support PRC.

**Comment by korydraughn** [comment]
Did you figure out the reason for that code change?

**Comment by JustinKyleJames** [comment]
> @JustinKyleJames - Please checkbox and close if complete. Thanks!

Beat me by 1 minute.  Done.
