### ISSUE TITLE
Install of 'unittest-xml-reporting==1.14.0' in test hook breaks tests

### ISSUE THREAD

**Issue by FifthPotato** [irods/irods_resource_plugin_s3#2211]
- [x] main
- [x] 4-3-stable

---

Happens on ubuntu 24. Fix is to delete the following line: 

https://github.com/irods/irods_resource_plugin_s3/blob/0304827fea9a4a8acfc6c68b18c69ae165a9dedd/irods_consortium_continuous_integration_test_hook.py#L45

**Comment by korydraughn** [comment]
@FifthPotato Please open PRs with the necessary fixes for main and 4-3-stable.

**Comment by alanking** [comment]
@FifthPotato - Please checkbox and close. Thanks
