### ISSUE TITLE
Use of self.assertEquals in test breaks tests

### ISSUE THREAD

**Issue by FifthPotato** [irods/irods_resource_plugin_s3#2213]
- [x] main
- [x] 4-3-stable

---

On ubuntu24.
`self.assertEquals` should be replaced with `self.assertEqual`.
https://github.com/irods/irods_resource_plugin_s3/blob/0304827fea9a4a8acfc6c68b18c69ae165a9dedd/packaging/resource_suite_s3_nocache.py#L1605

**Comment by alanking** [comment]
@FifthPotato - Please checkbox and close. Thanks
